# Generated by Django 5.1.5 on 2025-01-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="last_name",
        ),
        migrations.AddField(
            model_name="employee",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="ФИО"
            ),
        ),
    ]
